server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BianBianY/spring-config-center.git
          skip-ssl-validation: true
      label: master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

 #暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true